# Urban Horizon Theme - Background and foreground colors
background = #ecebea
foreground = #2f3a42

# Standard colors
palette = 0=#d6d8db
palette = 1=#8a6f5c
palette = 2=#7f9186
palette = 3=#b29f7f
palette = 4=#5f7888
palette = 5=#7f8795
palette = 6=#8a6f5c
palette = 7=#46545d

# Bright colors
palette = 8=#9fa7ae
palette = 9=#9e8270
palette = 10=#93a79b
palette = 11=#c4b392
palette = 12=#7892a5
palette = 13=#99a2af
palette = 14=#9e8270
palette = 15=#223039
