$color = rgba(236, 235, 234, 1)
$inner_color = rgba(236, 235, 234, 0.66)
$outer_color = rgba(138, 111, 92, 1)
$font_color = rgba(47, 58, 66, 1)
$placeholder_color = rgba(70, 84, 93, 0.7)
$check_color = rgba(127, 145, 134, 1)
