# Urban Horizon Theme - Kitty Terminal

background            #ecebea
foreground            #2f3a42

# black
color0  #d6d8db
color8  #9fa7ae

# red
color1  #8a6f5c
color9  #9e8270

# green
color2  #7f9186
color10 #93a79b

# yellow
color3  #b29f7f
color11 #c4b392

# blue
color4  #5f7888
color12 #7892a5

# magenta
color5  #7f8795
color13 #99a2af

#cyan
color6  #8a6f5c
color14 #9e8270

#white
color7  #46545d
color15 #223039

#Cursor
cursor_trail 1
